### ISSUE TITLE
release_checker uses wrong rosdistro repo

### ISSUE THREAD

**Issue by DLu** [awslabs/ros2-migration-tools#2]
The urls listed [here](https://github.com/awslabs/ros2-migration-tools/blob/master/ros2_migration/effort_estimation/ros2_release_checker.py#L22) are for [ros2/rosdistro](https://github.com/ros2/rosdistro/) but it should refer to [ros/rosdistro as of ](https://github.com/ros2/rosdistro/issues/492) as of January.

**Comment by AAlon** [comment]
Thank you for bringing this to our attention! Fixed and also dropped ardent in favor of crystal.

**Comment by AAlon** [comment]
@ https://github.com/awslabs/ros2-migration-tools/commit/5e05e07ca7de8a1bc858009799cb1152d9ff197b
